[package]
name = "rust-hyper-web"
version = "0.1.0"
authors = ["snwallet <snwallet@qq.com>"]
edition = "2018"


[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures-util = { version = "0.3", default-features = false }